language: go
go:
    # https://github.com/bradleyfalzon/gopherci/pull/102#pullrequestreview-52975203
    - 1.9rc1
# sudo for docker service
# https://docs.travis-ci.com/user/docker/
sudo: required
services:
    - docker
env:
    - GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcloud-GopherCI-dev.json
before_install:
    - openssl aes-256-cbc -K $encrypted_870f8d7239ea_key -iv $encrypted_870f8d7239ea_iv -in GopherCI-dev-81e88eb7fa6e.json.enc -out /tmp/gcloud-GopherCI-dev.json -d
    - docker pull gopherci/gopherci-env:latest
    - go get github.com/mattn/goveralls
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/golang/dep/cmd/dep
    - make deps
script:
    - $HOME/gopath/bin/goveralls -service=travis-ci
